import fs from 'fs'
import path from 'path'
import meta from './franka-arm.json'
import ArmStackClient from './ArmStackClient'

/* Generated by scripts/franka_to_svg.py; inlined so the animation can reach its groups. */
const SVG = fs.readFileSync(
    path.join(process.cwd(), 'src', 'app', 'blog', 'droid-one-pc', 'franka-arm.svg'),
    'utf8',
)

export default function ArmStack() {
    return <ArmStackClient svg={SVG} meta={meta} />
}
